[package]
name = "testing"
version = "0.1.0"
edition = "2021"

[dependencies]
fantoccini = "0.21.4"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"

[[bin]]
name = "testing"
path = "main.rs"