name: Web Driver CI

jobs:
  - name: Draft
    enable: on
    insts:
      - "@loc //input[@id='account']"
      - "@send admin"
      - "@loc //input[@id='password']"
      - "@send sei654321"
      - "@loc //button[span[text() = '登 录']]"
      - "@click"
      - "@loop //button[@aria-label='Close' and contains(@class, 'ant-modal-close')]"
      - "@click"
      - "@end ifloc"
